import { extractEventBaseUuid } from '@/utils/extractEventBaseUuid'
import { TIMEZONES } from '@/utils/timezone-data'
import ICAL from 'ical.js'
import { CounterProposalPayload, postCounterProposalRaw } from './EventDao'
import { CalendarEvent } from './EventsTypes'
import { makeTimezone, makeVevent } from './utils'
