# Build context: the e2e/ directory
ARG SABRE_IMAGE="linagora/esn-sabre:2.4.6.8"

FROM ${SABRE_IMAGE}

COPY src/test/resources/twake-calendar-side-service-conf/jwt_publickey /var/www/config/esn.key.pub
